보험 추가 기능 구현, db 스키마 작성 완료, 보험 추천 관련 질문하기 기능 구현 완료
mju-likelion/hackathon-team1-server-nestjs pull request #4
Opened 2023-08-06 22:44 UTC by kMinsAlgorithm

위 기능 구현이 완료되었습니다.

위 보험 여러개, 하나 검색하기 기능과 질문하기 기능 이외에 프로젝트에 구현되어 있는 기능들은 프론트와 연결되지 않을 기능들이라고 생각하시면 될 것 같습니다.(예를 들어 보험 추가하기 기능은 프론트에서 연결하지 않을 예정이고 데이터셋이 변경될떄마다 postman으로 찔러서 사용할 예정입니다.)

db insuranceInfo의 속성들에 대한 설명은 
| 속성명                 | 설명                                                     | 데이터 타입  |
|-----------------------|----------------------------------------------------------|--------------|
| infoId                 | 보험 정보 ID                                              | 문자열 (String) |
| insuranceLogoId        | 보험사 로고 ID                                            | 문자열 (String) |
| premiumMale            | 남성 보험료                                               | 정수 (Integer) |
| premiumFemale          | 여성 보험료                                               | 정수 (Integer) |
| insuranceAgeGroupStart | 보험 가입 연령대 시작                                     | 정수 (Integer) |
| insuranceAgeGroupEnd   | 보험 가입 연령대 종료                                     | 정수 (Integer) |
| insuranceAgeGroup      | 보험 가입 연령대                                          | 정수 (Integer) |
| companyName           | 보험사 이름                                               | 문자열 (String) |
| productName            | 보험 상품 이름                                            | 문자열 (String) |
| insuranceType          | 보험 유형                                                 | 문자열 (String) |
| registrationType       | 가입 방법                                                 | 문자열 (String) |
| registrationLink       | 가입 링크                                                 | 문자열 (String) |
| premiumRenewable       | 보험료 갱신 가능 여부                                    | 논리값 (Boolean) |
| cancellationRefund     | 해지 환급금                                               | 실수 (Float)  |
| cancellationPeriod     | 해지 기간                                                 | 정수 (Integer) |
| priceIndex             | 가격 지수                                                 | 실수 (Float)  |
| depositorProtection    | 예금자 보호 상품 금액                                     | 정수 (Integer) |
| guaranteeInsurance     | 보장 보험 포함 여부                                       | 논리값 (Boolean) |
| actualLossCoverage     | 실손 보험 포함 여부                                       | 논리값 (Boolean) |
| fixedInterestRate      | 고정 이자율                                               | 논리값 (Boolean) |

다음과 같습니다.

해당 api의 구현 예시는 api 문서에 자세하게 명시하였지만 예시 사진 첨부합니다.
![image](https://github.com/mju-likelion/hackathon-team1-server-nestjs/assets/84526709/146a281d-7598-4c10-a20f-620dd1517de0)
![image](https://github.com/mju-likelion/hackathon-team1-server-nestjs/assets/84526709/444493e3-24a2-41c2-b89b-e648f1022760)

2023-08-07 15:06 UTC, harksu requested changes
혼자서 서버 작업하느라 고생이 너무 많습니다. 
작업속도가 정말 빠르기도하고, 프리즈마 관련해서는 저도 적용을 해본적이 없어서 다소 부족할 순 있지만 그래도 이런 저런 커멘트들 참고해보시면 좋을 것 같아요! 

+++ a 라고 이름 지으면 진짜 다음에 혼납니다

2023-08-07 15:06 UTC, harksu commented on prisma/schema.prisma
>    logoId     String          @id @default(uuid())
👍

2023-08-07 15:06 UTC, harksu commented on prisma/schema.prisma
> +  infoId                  String        @id @default(uuid())
보통은 그냥 id라고 하거나, insuranceId라고 하지요

2023-08-07 15:06 UTC, harksu commented on prisma/schema.prisma
> +  insuranceLogo           InsuranceLogo @relation(fields: [insuranceLogoId], references: [logoId])
이렇게 쭉 나열되어 있는 속성들 같은 경우는 prefix를 기준으로 동일한 것들 끼리 순서대로 나열 하면 가독성이 좋아집니다!

insurance에 해당하는 속성들을 순서대로 나열하면 보기에 더 가독성이 좋아질 것 같아요

2023-08-07 15:06 UTC, harksu commented on prisma/schema.prisma
> +  insuranceLogo           InsuranceLogo @relation(fields: [insuranceLogoId], references: [logoId])
+++index라는 이름에 float 가 맞는지는 고민이 다소 필요해 보입니다

2023-08-07 15:06 UTC, harksu commented on prisma/schema.prisma
> +  insuranceLogo           InsuranceLogo @relation(fields: [insuranceLogoId], references: [logoId])
속성이 좀 많아서 이에 대한 얘외 케이스 관리가 잘 되어야 할 것으로 보여져요!

2023-08-07 15:06 UTC, harksu commented on src/insurance-suggesters/dto/create-insurance.dto.ts
> +  readonly fixedInterestRate: boolean = false;
이건 무슨 의도인가욤 ? 🤔

2023-08-07 15:06 UTC, harksu commented on src/insurance-suggesters/insurance-suggesters.controller.ts
>      return this.insuranceSuggestersService.createInsurance(createInsuranceDto);
~tersService라는 이름이 다소 어색하긴한데.. 모델을 사용해서 ters라는 이름을 가져간건가요?

2023-08-07 15:06 UTC, harksu commented on src/insurance-suggesters/insurance-suggesters.controller.ts
> +  @Post('/delete-insurances')
delete요청이 왜 @Post decorator?

2023-08-07 15:06 UTC, harksu commented on src/insurance-suggesters/insurance-suggesters.service.ts
> +      'http://127.0.0.1:8000/recommendations',
아무리 localhost라고 하더라도, 환경변수로 분리해주세요!

2023-08-07 15:06 UTC, harksu commented on src/insurance-suggesters/insurance-suggesters.service.ts
> +      'http://127.0.0.1:8000/recommendations',
그리고 해당 요청이 실패했을 때 catch도 필요할 것 같습니다

2023-08-07 15:06 UTC, harksu commented on src/insurance-suggesters/insurance-suggesters.service.ts
> +    const insuranceIds = response.data;
받는 상수의 이름은 복수형 거기에 대입되는 data는 단수형은 안맞지요 :(

2023-08-07 15:06 UTC, harksu commented on src/insurance-suggesters/insurance-suggesters.service.ts
> +    const a: { [key: string]: string } = {
a라는 네이밍은 안돼요 🔥

2023-08-07 15:06 UTC, harksu commented on src/insurance-suggesters/insurance-suggesters.service.ts
> +    const a: { [key: string]: string } = {
차라리 INSURANCE_KEY_VALUE_OBJECT정도 어떨까요?

2023-08-07 15:06 UTC, harksu commented on src/insurance-suggesters/insurance-suggesters.service.ts
> +    // 보험사 이름으로 이미지 URL을 찾는 함수 원래 보험사 이름으로 db에서 검색하려고 했는데 안되더라구요?
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ... ㄱㅇㅇ..

2023-08-07 15:06 UTC, harksu commented on src/insurance-suggesters/insurance-suggesters.service.ts
> +      if (a.hasOwnProperty(companyName)) {
a 진짜 혼납니다 🔪

2023-08-08 04:28 UTC, kMinsAlgorithm commented on prisma/schema.prisma
> +  infoId                  String        @id @default(uuid())
바꾸겠습니당

2023-08-08 04:29 UTC, kMinsAlgorithm commented on prisma/schema.prisma
> +  insuranceLogo           InsuranceLogo @relation(fields: [insuranceLogoId], references: [logoId])
저게 보험 가격 지수? 로 퍼센테이지로 표시되어 있는 항목인데 이름을 수정하거나 고려해보겠습닏다.

2023-08-08 04:30 UTC, kMinsAlgorithm commented on src/insurance-suggesters/insurance-suggesters.controller.ts
>      return this.insuranceSuggestersService.createInsurance(createInsuranceDto);
넵 그렇긴 한데 저도 어색하긴 하네요..

2023-08-08 04:30 UTC, kMinsAlgorithm commented on src/insurance-suggesters/insurance-suggesters.controller.ts
> +  @Post('/delete-insurances')
어 뭐야 아 저거 테스트전용으로 만들다가 다쓰고 마지막에 delete로 바꿨는데 깜빡했네요..ㅎㅎ

2023-08-08 04:30 UTC, kMinsAlgorithm commented on src/insurance-suggesters/insurance-suggesters.service.ts
> +      'http://127.0.0.1:8000/recommendations',
넵 수정하겠습니다!

2023-08-10 18:01 UTC, merged